name: Pipeline Test

on:
  push:
    branches:
    - main

jobs:
  pipeline-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install requirements.txt
    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r ./main/project/requirements.txt

    # Set permissions    
    - name: Set execute permission on tests.sh
      run: chmod +x ./main/project/tests.sh
    
      # Run Pipeline Test 

    - name: Pipeline Test
      run: |
        ./main/project/tests.sh